version: "3.8"

networks:
  eCommerce:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: eCommerce-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - eCommerce
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: .
    container_name: eCommerce
    networks:
      - eCommerce
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./public/images:/eCommerce/public/images
    #environment:
    #DATABASE_URL: "postgresql://Mkhululi:Mvulane9876543210@db:5432/ecommerce?schema=public"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
